# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v0.5.1
_src_path: gh:FollowTheProcess/go_copier
author_email: null
author_name: Tom Fleet
create_github_repo: true
description: Semver parsing and validation library for Go
github_url: https://github.com/FollowTheProcess/semver
github_username: FollowTheProcess
initialise_git_repo: true
license: MIT License
project_name: Semver
project_slug: semver
project_type: library
